import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav
          style={{
            display: "flex",
            padding: "10px",
            justifyContent: "center",
            alignItems: "center",
            gap: "10px",
            fontSize: "23px",
          }}
        >
          <Link href={"/"}> Home</Link>
          <Link href={"/posts"}> Posts</Link>
          <Link href={"/articles"}> Articles</Link>
        </nav>
        <div>{children}</div>
      </body>
    </html>
  );
}
